/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>

int main(void)
{
//	System Handler Control and Status Register
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

//	Enabling the faults bits from 16 to 19
	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault

	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_adress) (void);

	some_adress = (void*)0x20010000;

	some_adress();

	for(;;);
}

void HardFault_Handler(void)
{
	printf("Exception : HardFault\n");
	while(1);
}
void MemManage_Handler(void)
{
	printf("Exception : MemFault\n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}

__attribute__ ((naked)) void UsageFault_Handler(void)
{
	__asm ("mrs r0,MSP");
	__asm ("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame)
{
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Exception : UsageFault\n");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF);
	printf("pBaseStackFrame = %p\n", pBaseStackFrame);
	printf("value of R0 = %lx\n",pBaseStackFrame[0]);
	printf("value of R1 = %lx\n",pBaseStackFrame[1]);
	printf("value of R2 = %lx\n",pBaseStackFrame[2]);
	printf("value of R3 = %lx\n",pBaseStackFrame[3]);
	printf("value of R12 = %lx\n",pBaseStackFrame[4]);
	printf("value of LR = %lx\n",pBaseStackFrame[5]);
	printf("value of PC = %lx\n",pBaseStackFrame[6]);
	printf("value of XPSR = %lx\n",pBaseStackFrame[7]);


	while(1);
}
